name: Build Java (Noble)

on:
    workflow_dispatch:
    push:
        branches:
            - main
        paths:
            - java-noble/**

permissions:
    actions: read
    packages: write

concurrency:
    group: 'java-noble-${{ github.ref }}'
    cancel-in-progress: true

jobs:
    push:
        name: "java_${{ matrix.tag }}_noble"
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                tag:
                    - 24
                    - perf_24
                    - 21
                    - perf_21
                    - 17
                    - perf_17
                    - 11
                    - perf_11
                    - 8
                    - perf_8
        
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: QEMU Setup
              uses: docker/setup-qemu-action@v3
            
            - name: Setup Buildx
              uses: docker/setup-buildx-action@v3
              with:
                buildkitd-flags: --debug
        
            - name: Login to registry
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.repository_owner }}
                password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and Push
              uses: docker/build-push-action@v6
              with:
                context: .
                platforms: linux/amd64,linux/arm64
                file: ./java/${{ matrix.tag }}/Dockerfile
                push: true
                tags: ghcr.io/skullians/native-leak-profiling:java_${{ matrix.tag }}_noble
                cache-from: type=gha
                cache-to: type=gha,mode=max
